# theme: jekyll-theme-minimal

domain: SooCities.github.io
url: https://SooCities.github.io/
baseurl: ""
title: Sounds of our Cities
description: SOUNDS OF OUR CITIES is a European project of cultural cooperation based upon research and the transfer of knowledge among the spheres of art, technology and social space.

collections:
  cities:
    output: true
    permalink: /:name
  projects:
    output: true
    permalink: /project/:name
  subpages:
    output: true
    permalink: /project/:name